#pragma once

#include "driver/gpio.h"
#include "driver/spi_master.h"
#include "driver/uart.h"

#define BOARD_LCD_H_RES 480
#define BOARD_LCD_V_RES 320
#define BOARD_LCD_DRAW_LINES 40
#define BOARD_LCD_PIXEL_CLOCK_HZ (10 * 1000 * 1000)

#define BOARD_LCD_DB0 GPIO_NUM_4
#define BOARD_LCD_DB1 GPIO_NUM_5
#define BOARD_LCD_DB2 GPIO_NUM_6
#define BOARD_LCD_DB3 GPIO_NUM_7
#define BOARD_LCD_DB4 GPIO_NUM_8
#define BOARD_LCD_DB5 GPIO_NUM_9
#define BOARD_LCD_DB6 GPIO_NUM_10
#define BOARD_LCD_DB7 GPIO_NUM_11
#define BOARD_LCD_DB8 GPIO_NUM_12
#define BOARD_LCD_DB9 GPIO_NUM_13
#define BOARD_LCD_DB10 GPIO_NUM_14
#define BOARD_LCD_DB11 GPIO_NUM_15
#define BOARD_LCD_DB12 GPIO_NUM_16
#define BOARD_LCD_DB13 GPIO_NUM_17
#define BOARD_LCD_DB14 GPIO_NUM_18
#define BOARD_LCD_DB15 GPIO_NUM_21

#define BOARD_LCD_WR GPIO_NUM_38
#define BOARD_LCD_DC GPIO_NUM_39
#define BOARD_LCD_CS GPIO_NUM_40
#define BOARD_LCD_RST GPIO_NUM_NC
#define BOARD_LCD_BL GPIO_NUM_NC
#define BOARD_LCD_RD GPIO_NUM_NC

#define BOARD_SHARED_SPI_HOST SPI3_HOST
#define BOARD_TOUCH_CS GPIO_NUM_1
#define BOARD_TOUCH_MOSI GPIO_NUM_42
#define BOARD_TOUCH_MISO GPIO_NUM_47
#define BOARD_TOUCH_SCLK GPIO_NUM_48
#define BOARD_TOUCH_IRQ GPIO_NUM_NC
#define BOARD_TOUCH_CLOCK_HZ (1 * 1000 * 1000)

#define BOARD_SD_CS GPIO_NUM_41
#define BOARD_SD_MOSI BOARD_TOUCH_MOSI
#define BOARD_SD_MISO BOARD_TOUCH_MISO
#define BOARD_SD_SCLK BOARD_TOUCH_SCLK
#define BOARD_SD_MOUNT_POINT "/sdcard"

#define BOARD_RS485_UART UART_NUM_2
#define BOARD_RS485_RX GPIO_NUM_3
#define BOARD_RS485_DE_RE GPIO_NUM_2
#define BOARD_RS485_TX GPIO_NUM_46
#define BOARD_RS485_BAUD_RATE 4800

#define BOARD_SIM_UART UART_NUM_1
#define BOARD_SIM_TX GPIO_NUM_43
#define BOARD_SIM_RX GPIO_NUM_44
#define BOARD_SIM_PWRKEY GPIO_NUM_45
#define BOARD_SIM_BAUD_RATE 115200
#define BOARD_SIM_PWRKEY_ACTIVE_LEVEL 1
#define BOARD_SIM_PWRKEY_INACTIVE_LEVEL 0

#define BOARD_BUTTON_BOOT GPIO_NUM_0
